sudo: required
services:
  - docker

before_install:
  - docker build -t sohaib629/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sohaib629/react-test npm test

after_success:
  - docker build -t sohaib629/multi-client ./client
  - docker build -t sohaib629/multi-nginx ./nginx
  - docker build -t sohaib629/multi-server ./server
  - docker build -t sohaib629/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sohaib629/multi-client
  - docker push sohaib629/multi-nginx
  - docker push sohaib629/multi-server
  - docker push sohaib629/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-687963397861'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
